# Generated by Django 2.0.2 on 2019-07-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('year', models.TextField(max_length=120)),
                ('brand', models.TextField(max_length=120)),
                ('extcolor', models.TextField(max_length=120)),
                ('intcolor', models.TextField(max_length=120)),
                ('transmission', models.TextField(max_length=120)),
                ('price', models.TextField(max_length=60)),
                ('phone', models.TextField(max_length=60)),
            ],
        ),
    ]
