# Generated by Django 2.0.2 on 2019-07-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': False},
        ),
    ]
