# Generated by Django 2.0.2 on 2019-07-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_auto_20190730_0207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
    ]
